# Generated by Django 4.0.1 on 2022-01-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_driver_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='max_number_of_passengers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
