# Generated by Django 4.0.1 on 2022-01-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_vehicle_max_number_of_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='max_number_of_passengers',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=256)),
                ('destination', models.CharField(max_length=256)),
                ('arrival_time_early', models.DateTimeField()),
                ('arrival_time_late', models.DateTimeField()),
                ('current_passenger_num', models.IntegerField()),
                ('vechicle_type', models.CharField(blank=True, default='', max_length=256)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('driver', models.CharField(max_length=256)),
                ('is_complete', models.BooleanField(default=False)),
                ('sharer', models.ManyToManyField(to='users.User')),
            ],
        ),
    ]
