# Generated by Django 4.0.1 on 2022-01-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_vehicle_max_number_of_passengers_ride'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='arrival_time_late',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_number',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='special_request',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(default='', max_length=256),
        ),
    ]
