# Generated by Django 4.0.1 on 2022-01-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_ride_arrival_time_late_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
