# Generated by Django 4.0.1 on 2022-01-28 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_ride_is_shared'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='vechicle_type',
            new_name='vehicle_type',
        ),
    ]
